
<div>
    <select class="prefix" name="prefix">
        <option value="1" {{ old('prefix') == '1' ? 'selected' : '' }}>+1</option>
        <option value="20" {{ old('prefix') == '20' ? 'selected' : '' }}>+20</option>
        <option value="30" {{ old('prefix') == '30' ? 'selected' : '' }}>+30</option>
        <option value="31" {{ old('prefix') == '31' ? 'selected' : '' }}>+31</option>
        <option value="32" {{ old('prefix') == '32' ? 'selected' : '' }}>+32</option>
        <option value="33" {{ old('prefix') == '33' ? 'selected' : '' }}>+33</option>
        <option value="34" {{ old('prefix') == '34' ? 'selected' : '' }}>+34</option>
        <option value="36" {{ old('prefix') == '36' ? 'selected' : '' }}>+36</option>
        <option value="39" {{ old('prefix') == '39' ? 'selected' : '' }}>+39</option>
        <option value="40" {{ old('prefix') == '40' ? 'selected' : '' }}>+40</option>
        <option value="41" {{ old('prefix') == '41' ? 'selected' : '' }}>+41</option>
        <option value="43" {{ old('prefix') == '43' ? 'selected' : '' }}>+43</option>
        <option value="44" {{ old('prefix') == '44' ? 'selected' : '' }}>+44</option>
        <option value="45" {{ old('prefix') == '45' ? 'selected' : '' }}>+45</option>
        <option value="46" {{ old('prefix') == '46' ? 'selected' : '' }}>+46</option>
        <option value="47" {{ old('prefix') == '47' ? 'selected' : '' }}>+47</option>
        <option value="48" {{ old('prefix') == '48' ? 'selected' : '' }}>+48</option>
        <option value="49" {{ old('prefix') == '49' ? 'selected' : '' }}>+49</option>
        <option value="51" {{ old('prefix') == '51' ? 'selected' : '' }}>+51</option>
        <option value="52" {{ old('prefix') == '52' ? 'selected' : '' }}>+52</option>
        <option value="53" {{ old('prefix') == '53' ? 'selected' : '' }}>+53</option>
        <option value="54" {{ old('prefix') == '54' ? 'selected' : '' }}>+54</option>
        <option value="55" {{ old('prefix') == '55' ? 'selected' : '' }}>+55</option>
        <option value="56" {{ old('prefix') == '56' ? 'selected' : '' }}>+56</option>
        <option value="57" {{ old('prefix') == '57' ? 'selected' : '' }}>+57</option>
        <option value="58" {{ old('prefix') == '58' ? 'selected' : '' }}>+58</option>
        <option value="60" {{ old('prefix') == '60' ? 'selected' : '' }}>+60</option>
        <option value="61" {{ old('prefix') == '61' ? 'selected' : '' }}>+61</option>
        <option value="62" {{ old('prefix') == '62' ? 'selected' : '' }}>+62</option>
        <option value="63" {{ old('prefix') == '63' ? 'selected' : '' }}>+63</option>
        <option value="64" {{ old('prefix') == '64' ? 'selected' : '' }}>+64</option>
        <option value="65" {{ old('prefix') == '65' ? 'selected' : '' }}>+65</option>
        <option value="66" {{ old('prefix') == '66' ? 'selected' : '' }}>+66</option>
        <option value="81" {{ old('prefix') == '81' ? 'selected' : '' }}>+81</option>
        <option value="82" {{ old('prefix') == '82' ? 'selected' : '' }}>+82</option>
        <option value="84" {{ old('prefix') == '84' ? 'selected' : '' }}>+84</option>
        <option value="86" {{ old('prefix') == '86' ? 'selected' : '' }}>+86</option>
        <option value="90" {{ old('prefix') == '90' ? 'selected' : '' }}>+90</option>
        <option value="91" {{ old('prefix') == '91' ? 'selected' : '' }}>+91</option>
        <option value="92" {{ old('prefix') == '92' ? 'selected' : '' }}>+92</option>
        <option value="93" {{ old('prefix') == '93' ? 'selected' : '' }}>+93</option>
        <option value="94" {{ old('prefix') == '94' ? 'selected' : '' }}>+94</option>
        <option value="95" {{ old('prefix') == '95' ? 'selected' : '' }}>+95</option>
        <option value="98" {{ old('prefix') == '98' ? 'selected' : '' }}>+98</option>
        <option value="211" {{ old('prefix') == '211' ? 'selected' : '' }}>+211</option>
        <option value="212" {{ old('prefix') == '212' ? 'selected' : '' }}>+212</option>
        <option value="213" {{ old('prefix') == '213' ? 'selected' : '' }}>+213</option>
        <option value="216" {{ old('prefix') == '216' ? 'selected' : '' }}>+216</option>
        <option value="218" {{ old('prefix') == '218' ? 'selected' : '' }}>+218</option>
        <option value="220" {{ old('prefix') == '220' ? 'selected' : '' }}>+220</option>
        <option value="221" {{ old('prefix') == '221' ? 'selected' : '' }}>+221</option>
        <option value="222" {{ old('prefix') == '222' ? 'selected' : '' }}>+222</option>
        <option value="223" {{ old('prefix') == '223' ? 'selected' : '' }}>+223</option>
        <option value="224" {{ old('prefix') == '224' ? 'selected' : '' }}>+224</option>
        <option value="225" {{ old('prefix') == '225' ? 'selected' : '' }}>+225</option>
        <option value="226" {{ old('prefix') == '226' ? 'selected' : '' }}>+226</option>
        <option value="227" {{ old('prefix') == '227' ? 'selected' : '' }}>+227</option>
        <option value="228" {{ old('prefix') == '228' ? 'selected' : '' }}>+228</option>
        <option value="229" {{ old('prefix') == '229' ? 'selected' : '' }}>+229</option>
        <option value="230" {{ old('prefix') == '230' ? 'selected' : '' }}>+230</option>
        <option value="231" {{ old('prefix') == '231' ? 'selected' : '' }}>+231</option>
        <option value="232" {{ old('prefix') == '232' ? 'selected' : '' }}>+232</option>
        <option value="233" {{ old('prefix') == '233' ? 'selected' : '' }}>+233</option>
        <option value="234" {{ old('prefix') == '234' ? 'selected' : '' }}>+234</option>
        <option value="235" {{ old('prefix') == '235' ? 'selected' : '' }}>+235</option>
        <option value="236" {{ old('prefix') == '236' ? 'selected' : '' }}>+236</option>
        <option value="237" {{ old('prefix') == '237' ? 'selected' : '' }}>+237</option>
        <option value="238" {{ old('prefix') == '238' ? 'selected' : '' }}>+238</option>
        <option value="239" {{ old('prefix') == '239' ? 'selected' : '' }}>+239</option>
        <option value="240" {{ old('prefix') == '240' ? 'selected' : '' }}>+240</option>
        <option value="241" {{ old('prefix') == '241' ? 'selected' : '' }}>+241</option>
        <option value="242" {{ old('prefix') == '242' ? 'selected' : '' }}>+242</option>
        <option value="243" {{ old('prefix') == '243' ? 'selected' : '' }}>+243</option>
        <option value="244" {{ old('prefix') == '244' ? 'selected' : '' }}>+244</option>
        <option value="245" {{ old('prefix') == '245' ? 'selected' : '' }}>+245</option>
        <option value="246" {{ old('prefix') == '246' ? 'selected' : '' }}>+246</option>
        <option value="248" {{ old('prefix') == '248' ? 'selected' : '' }}>+248</option>
        <option value="249" {{ old('prefix') == '249' ? 'selected' : '' }}>+249</option>
        <option value="250" {{ old('prefix') == '250' ? 'selected' : '' }}>+250</option>
        <option value="251" {{ old('prefix') == '251' ? 'selected' : '' }}>+251</option>
        <option value="252" {{ old('prefix') == '252' ? 'selected' : '' }}>+252</option>
        <option value="253" {{ old('prefix') == '253' ? 'selected' : '' }}>+253</option>
        <option value="254" {{ old('prefix') == '254' ? 'selected' : '' }}>+254</option>
        <option value="255" {{ old('prefix') == '255' ? 'selected' : '' }}>+255</option>
        <option value="256" {{ old('prefix') == '256' ? 'selected' : '' }}>+256</option>
        <option value="257" {{ old('prefix') == '257' ? 'selected' : '' }}>+257</option>
        <option value="258" {{ old('prefix') == '258' ? 'selected' : '' }}>+258</option>
        <option value="260" {{ old('prefix') == '260' ? 'selected' : '' }}>+260</option>
        <option value="261" {{ old('prefix') == '261' ? 'selected' : '' }}>+261</option>
        <option value="262" {{ old('prefix') == '262' ? 'selected' : '' }}>+262</option>
        <option value="263" {{ old('prefix') == '263' ? 'selected' : '' }}>+263</option>
        <option value="264" {{ old('prefix') == '264' ? 'selected' : '' }}>+264</option>
        <option value="265" {{ old('prefix') == '265' ? 'selected' : '' }}>+265</option>
        <option value="266" {{ old('prefix') == '266' ? 'selected' : '' }}>+266</option>
        <option value="267" {{ old('prefix') == '267' ? 'selected' : '' }}>+267</option>
        <option value="268" {{ old('prefix') == '268' ? 'selected' : '' }}>+268</option>
        <option value="269" {{ old('prefix') == '269' ? 'selected' : '' }}>+269</option>
        <option value="290" {{ old('prefix') == '290' ? 'selected' : '' }}>+290</option>
        <option value="291" {{ old('prefix') == '291' ? 'selected' : '' }}>+291</option>
        <option value="297" {{ old('prefix') == '297' ? 'selected' : '' }}>+297</option>
        <option value="298" {{ old('prefix') == '298' ? 'selected' : '' }}>+298</option>
        <option value="299" {{ old('prefix') == '299' ? 'selected' : '' }}>+299</option>
        <option value="350" {{ old('prefix') == '350' ? 'selected' : '' }}>+350</option>
        <option value="351" {{ old('prefix', '351') == '351' ? 'selected' : '' }}>+351</option>
        <option value="352" {{ old('prefix') == '352' ? 'selected' : '' }}>+352</option>
        <option value="353" {{ old('prefix') == '353' ? 'selected' : '' }}>+353</option>
        <option value="354" {{ old('prefix') == '354' ? 'selected' : '' }}>+354</option>
        <option value="355" {{ old('prefix') == '355' ? 'selected' : '' }}>+355</option>
        <option value="356" {{ old('prefix') == '356' ? 'selected' : '' }}>+356</option>
        <option value="357" {{ old('prefix') == '357' ? 'selected' : '' }}>+357</option>
        <option value="358" {{ old('prefix') == '358' ? 'selected' : '' }}>+358</option>
        <option value="359" {{ old('prefix') == '359' ? 'selected' : '' }}>+359</option>
        <option value="370" {{ old('prefix') == '370' ? 'selected' : '' }}>+370</option>
        <option value="371" {{ old('prefix') == '371' ? 'selected' : '' }}>+371</option>
        <option value="372" {{ old('prefix') == '372' ? 'selected' : '' }}>+372</option>
        <option value="373" {{ old('prefix') == '373' ? 'selected' : '' }}>+373</option>
        <option value="374" {{ old('prefix') == '374' ? 'selected' : '' }}>+374</option>
        <option value="375" {{ old('prefix') == '375' ? 'selected' : '' }}>+375</option>
        <option value="376" {{ old('prefix') == '376' ? 'selected' : '' }}>+376</option>
        <option value="377" {{ old('prefix') == '377' ? 'selected' : '' }}>+377</option>
        <option value="378" {{ old('prefix') == '378' ? 'selected' : '' }}>+378</option>
        <option value="379" {{ old('prefix') == '379' ? 'selected' : '' }}>+379</option>
        <option value="380" {{ old('prefix') == '380' ? 'selected' : '' }}>+380</option>
        <option value="381" {{ old('prefix') == '381' ? 'selected' : '' }}>+381</option>
        <option value="382" {{ old('prefix') == '382' ? 'selected' : '' }}>+382</option>
        <option value="383" {{ old('prefix') == '383' ? 'selected' : '' }}>+383</option>
        <option value="385" {{ old('prefix') == '385' ? 'selected' : '' }}>+385</option>
        <option value="386" {{ old('prefix') == '386' ? 'selected' : '' }}>+386</option>
        <option value="387" {{ old('prefix') == '387' ? 'selected' : '' }}>+387</option>
        <option value="389" {{ old('prefix') == '389' ? 'selected' : '' }}>+389</option>
        <option value="420" {{ old('prefix') == '420' ? 'selected' : '' }}>+420</option>
        <option value="421" {{ old('prefix') == '421' ? 'selected' : '' }}>+421</option>
        <option value="423" {{ old('prefix') == '423' ? 'selected' : '' }}>+423</option>
        <option value="500" {{ old('prefix') == '500' ? 'selected' : '' }}>+500</option>
        <option value="501" {{ old('prefix') == '501' ? 'selected' : '' }}>+501</option>
        <option value="502" {{ old('prefix') == '502' ? 'selected' : '' }}>+502</option>
        <option value="503" {{ old('prefix') == '503' ? 'selected' : '' }}>+503</option>
        <option value="504" {{ old('prefix') == '504' ? 'selected' : '' }}>+504</option>
        <option value="505" {{ old('prefix') == '505' ? 'selected' : '' }}>+505</option>
        <option value="506" {{ old('prefix') == '506' ? 'selected' : '' }}>+506</option>
        <option value="507" {{ old('prefix') == '507' ? 'selected' : '' }}>+507</option>
        <option value="508" {{ old('prefix') == '508' ? 'selected' : '' }}>+508</option>
        <option value="509" {{ old('prefix') == '509' ? 'selected' : '' }}>+509</option>
        <option value="590" {{ old('prefix') == '590' ? 'selected' : '' }}>+590</option>
        <option value="591" {{ old('prefix') == '591' ? 'selected' : '' }}>+591</option>
        <option value="592" {{ old('prefix') == '592' ? 'selected' : '' }}>+592</option>
        <option value="593" {{ old('prefix') == '593' ? 'selected' : '' }}>+593</option>
        <option value="594" {{ old('prefix') == '594' ? 'selected' : '' }}>+594</option>
        <option value="595" {{ old('prefix') == '595' ? 'selected' : '' }}>+595</option>
        <option value="596" {{ old('prefix') == '596' ? 'selected' : '' }}>+596</option>
        <option value="597" {{ old('prefix') == '597' ? 'selected' : '' }}>+597</option>
        <option value="598" {{ old('prefix') == '598' ? 'selected' : '' }}>+598</option>
        <option value="599" {{ old('prefix') == '599' ? 'selected' : '' }}>+599</option>
        <option value="670" {{ old('prefix') == '670' ? 'selected' : '' }}>+670</option>
        <option value="672" {{ old('prefix') == '672' ? 'selected' : '' }}>+672</option>
        <option value="673" {{ old('prefix') == '673' ? 'selected' : '' }}>+673</option>
        <option value="674" {{ old('prefix') == '674' ? 'selected' : '' }}>+674</option>
        <option value="675" {{ old('prefix') == '675' ? 'selected' : '' }}>+675</option>
        <option value="676" {{ old('prefix') == '676' ? 'selected' : '' }}>+676</option>
        <option value="677" {{ old('prefix') == '677' ? 'selected' : '' }}>+677</option>
        <option value="678" {{ old('prefix') == '678' ? 'selected' : '' }}>+678</option>
        <option value="679" {{ old('prefix') == '679' ? 'selected' : '' }}>+679</option>
        <option value="680" {{ old('prefix') == '680' ? 'selected' : '' }}>+680</option>
        <option value="681" {{ old('prefix') == '681' ? 'selected' : '' }}>+681</option>
        <option value="682" {{ old('prefix') == '682' ? 'selected' : '' }}>+682</option>
        <option value="683" {{ old('prefix') == '683' ? 'selected' : '' }}>+683</option>
        <option value="685" {{ old('prefix') == '685' ? 'selected' : '' }}>+685</option>
        <option value="686" {{ old('prefix') == '686' ? 'selected' : '' }}>+686</option>
        <option value="687" {{ old('prefix') == '687' ? 'selected' : '' }}>+687</option>
        <option value="688" {{ old('prefix') == '688' ? 'selected' : '' }}>+688</option>
        <option value="689" {{ old('prefix') == '689' ? 'selected' : '' }}>+689</option>
        <option value="690" {{ old('prefix') == '690' ? 'selected' : '' }}>+690</option>
        <option value="691" {{ old('prefix') == '691' ? 'selected' : '' }}>+691</option>
        <option value="692" {{ old('prefix') == '692' ? 'selected' : '' }}>+692</option>
        <option value="850" {{ old('prefix') == '850' ? 'selected' : '' }}>+850</option>
        <option value="852" {{ old('prefix') == '852' ? 'selected' : '' }}>+852</option>
        <option value="853" {{ old('prefix') == '853' ? 'selected' : '' }}>+853</option>
        <option value="855" {{ old('prefix') == '855' ? 'selected' : '' }}>+855</option>
        <option value="856" {{ old('prefix') == '856' ? 'selected' : '' }}>+856</option>
        <option value="880" {{ old('prefix') == '880' ? 'selected' : '' }}>+880</option>
        <option value="886" {{ old('prefix') == '886' ? 'selected' : '' }}>+886</option>
        <option value="960" {{ old('prefix') == '960' ? 'selected' : '' }}>+960</option>
        <option value="961" {{ old('prefix') == '961' ? 'selected' : '' }}>+961</option>
        <option value="962" {{ old('prefix') == '962' ? 'selected' : '' }}>+962</option>
        <option value="963" {{ old('prefix') == '963' ? 'selected' : '' }}>+963</option>
        <option value="964" {{ old('prefix') == '964' ? 'selected' : '' }}>+964</option>
        <option value="965" {{ old('prefix') == '965' ? 'selected' : '' }}>+965</option>
        <option value="966" {{ old('prefix') == '966' ? 'selected' : '' }}>+966</option>
        <option value="967" {{ old('prefix') == '967' ? 'selected' : '' }}>+967</option>
        <option value="968" {{ old('prefix') == '968' ? 'selected' : '' }}>+968</option>
        <option value="970" {{ old('prefix') == '970' ? 'selected' : '' }}>+970</option>
        <option value="971" {{ old('prefix') == '971' ? 'selected' : '' }}>+971</option>
        <option value="972" {{ old('prefix') == '972' ? 'selected' : '' }}>+972</option>
        <option value="973" {{ old('prefix') == '973' ? 'selected' : '' }}>+973</option>
        <option value="974" {{ old('prefix') == '974' ? 'selected' : '' }}>+974</option>
        <option value="975" {{ old('prefix') == '975' ? 'selected' : '' }}>+975</option>
        <option value="976" {{ old('prefix') == '976' ? 'selected' : '' }}>+976</option>
        <option value="977" {{ old('prefix') == '977' ? 'selected' : '' }}>+977</option>
        <option value="992" {{ old('prefix') == '992' ? 'selected' : '' }}>+992</option>
        <option value="993" {{ old('prefix') == '993' ? 'selected' : '' }}>+993</option>
        <option value="994" {{ old('prefix') == '994' ? 'selected' : '' }}>+994</option>
        <option value="995" {{ old('prefix') == '995' ? 'selected' : '' }}>+995</option>
        <option value="996" {{ old('prefix') == '996' ? 'selected' : '' }}>+996</option>
        <option value="998" {{ old('prefix') == '998' ? 'selected' : '' }}>+998</option>
    </select>
</div>